FROM mhart/alpine-node

RUN npm install -g bower

RUN apk update && apk add git

RUN mkdir /app
ADD bower.json /app/bower.json

WORKDIR /app

VOLUME /app/bower_components

CMD bower install --allow-root
